name: Build Project

on:
  #push:
    #branches: main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file java-maven-sonar-argocd-helm-k8s/spring-boot-app/pom.xml

      - name: Run Tests
        run: mvn test
      
